### ISSUE TITLE
need a better color

### ISSUE THREAD

**Issue by bluelovers** [klesun/deep-js-completion#14]
color is too dark and maybe `[Symbol.iterator]` should not in first one

![image](https://user-images.githubusercontent.com/167966/57404036-99ae7780-720d-11e9-9e88-9da2d62dd06b.png)

**Comment by klesun** [comment]
Thanks for the suggestion.
The greyed out options are a _so-so_ prototype property suggestion, that are likely to be wrong, so they are grey on purpose, but I can make them a bit brighter.
The `[Symbol.iterator]` suggestion on your screenshot seems to come from IDEA itself, not from my plugin, but I'll take a look if I'm the reason of it's ordering.

**Comment by klesun** [comment]
wowoww, wait, is it typescript or flow on your screenshot? Sorry, my bad, the plugin is supposed to only run on vanilla js, I'll stop it from making suggestions in the statically typed js flavours.

**Comment by klesun** [comment]
Changed the greyed option color from 128,128,128 to 150,150,150: (will be deployed in few days)
![image](https://user-images.githubusercontent.com/5202330/57410619-f7ce6100-71f3-11e9-9de1-fc90e15781d5.png)

The `[Symbol.iterator]` issue should have been fixed in [2019.05.08.001](https://plugins.jetbrains.com/plugin/11478-deep-js-completion/update/61970) which was published by jetbrains few hours ago.

**Comment by klesun** [comment]
For history, there is now an option to enable plugin in typescript back: 
_File -> Settings ->Languages & Frameworks -> JavaScript -> deep-js-completion_

![image](https://user-images.githubusercontent.com/5202330/66702313-c81d0b00-ecf5-11e9-861d-34f7a9d70382.png)
